//#define RETRO_TAPPING
//#define IGNORE_MOD_TAP_INTERRUPT
#define PERMISSIVE_HOLD

//#define CHARYBDIS_MINIMUM_DEFAULT_DPI 1200
//#define CHARYBDIS_DEFAULT_DPI_CONFIG_STEP 400
//#define CHARYBDIS_MINIMUM_SNIPING_DPI 200
//#define CHARYBDIS_SNIPING_DPI_CONFIG_STEP 100
//#define POINTING_DEVICE_RIGHT

#define SPLIT_LAYER_STATE_ENABLE
#define CHARYBDIS_CONFIG_SYNC

#define NKRO_ENABLE
#define MOUSE_EXTENDED_REPORT
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
