#define PERMISSIVE_HOLD
#define TAPPING_FORCE_HOLD  //apparently deprecated and does nothing
#define QUICK_TAP_TERM 0  //does what TAPPING_FORCE_HOLD is supposed to do
#define COMBO_STRICT_TIMER

//#define CHARYBDIS_MINIMUM_DEFAULT_DPI 1200
//#define CHARYBDIS_DEFAULT_DPI_CONFIG_STEP 400
//#define CHARYBDIS_MINIMUM_SNIPING_DPI 200
//#define CHARYBDIS_SNIPING_DPI_CONFIG_STEP 100
//#define POINTING_DEVICE_RIGHT

#define SPLIT_LAYER_STATE_ENABLE
#define CHARYBDIS_CONFIG_SYNC

#define NKRO_ENABLE
#define MOUSE_EXTENDED_REPORT
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_THRESHOLD 300

#define COMBO_TERM 25
#define COMBO_ONLY_ON_LAYER 0

#define USB_SUSPEND_WAKEUP_DELAY 200
#define USB_POLLING_INTERVAL_MS 5



